# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvtongui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 50, 251, 421))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.carid = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.carid.setFont(font)
        self.carid.setObjectName("carid")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carid)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cartype = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cartype.setFont(font)
        self.cartype.setObjectName("cartype")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.cartype.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cartype)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.weight = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.weight.setFont(font)
        self.weight.setObjectName("weight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.weight)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.driveinplace = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.driveinplace.setFont(font)
        self.driveinplace.setObjectName("driveinplace")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.driveinplace)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.driveoutplace = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.driveoutplace.setFont(font)
        self.driveoutplace.setObjectName("driveoutplace")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.driveoutplace)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.goods = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.goods.setFont(font)
        self.goods.setObjectName("goods")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.goods)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.axle = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.axle.setFont(font)
        self.axle.setMaximum(8)
        self.axle.setObjectName("axle")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.axle)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.amount = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.amount.setFont(font)
        self.amount.setObjectName("amount")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.amount)
        self.time = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.time)
        self.calculateillegal = QtWidgets.QPushButton(self.centralwidget)
        self.calculateillegal.setGeometry(QtCore.QRect(40, 490, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.calculateillegal.setFont(font)
        self.calculateillegal.setObjectName("calculateillegal")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 50, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 100, 511, 351))
        self.label_7.setStyleSheet("image: url(:/carsnapshot/image/jihuo5.jpg);\n"
"border-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.store2mysql = QtWidgets.QPushButton(self.centralwidget)
        self.store2mysql.setGeometry(QtCore.QRect(180, 490, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.store2mysql.setFont(font)
        self.store2mysql.setObjectName("store2mysql")
        self.label_7.raise_()
        self.formLayoutWidget.raise_()
        self.calculateillegal.raise_()
        self.label_6.raise_()
        self.store2mysql.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 23))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mysqlquerymode = QtWidgets.QAction(MainWindow)
        self.mysqlquerymode.setObjectName("mysqlquerymode")
        self.read_associate = QtWidgets.QAction(MainWindow)
        self.read_associate.setObjectName("read_associate")
        self.read_help = QtWidgets.QAction(MainWindow)
        self.read_help.setObjectName("read_help")
        self.mysql_pattern = QtWidgets.QAction(MainWindow)
        self.mysql_pattern.setObjectName("mysql_pattern")
        self.mine_rules = QtWidgets.QAction(MainWindow)
        self.mine_rules.setObjectName("mine_rules")
        self.update_modelparams = QtWidgets.QAction(MainWindow)
        self.update_modelparams.setObjectName("update_modelparams")
        self.user_info = QtWidgets.QAction(MainWindow)
        self.user_info.setObjectName("user_info")
        self.read_soft_info = QtWidgets.QAction(MainWindow)
        self.read_soft_info.setObjectName("read_soft_info")
        self.menu_2.addAction(self.read_associate)
        self.menu_2.addAction(self.read_help)
        self.menu_2.addAction(self.read_soft_info)
        self.menu_3.addAction(self.user_info)
        self.menu.addAction(self.mysql_pattern)
        self.menu.addSeparator()
        self.menu.addAction(self.mine_rules)
        self.menu.addAction(self.update_modelparams)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SunShine_绿通"))
        self.label.setText(_translate("MainWindow", "车牌号"))
        self.label_2.setText(_translate("MainWindow", "车型"))
        self.cartype.setCurrentText(_translate("MainWindow", "计货1"))
        self.cartype.setItemText(0, _translate("MainWindow", "计货1"))
        self.cartype.setItemText(1, _translate("MainWindow", "计货2"))
        self.cartype.setItemText(2, _translate("MainWindow", "计货3"))
        self.cartype.setItemText(3, _translate("MainWindow", "计货4"))
        self.cartype.setItemText(4, _translate("MainWindow", "计货5"))
        self.cartype.setItemText(5, _translate("MainWindow", "一型货"))
        self.cartype.setItemText(6, _translate("MainWindow", "二型货"))
        self.cartype.setItemText(7, _translate("MainWindow", "三型货"))
        self.cartype.setItemText(8, _translate("MainWindow", "四型货"))
        self.cartype.setItemText(9, _translate("MainWindow", "五型货"))
        self.cartype.setItemText(10, _translate("MainWindow", "一型车"))
        self.cartype.setItemText(11, _translate("MainWindow", "二型车"))
        self.cartype.setItemText(12, _translate("MainWindow", "三型车"))
        self.cartype.setItemText(13, _translate("MainWindow", "四型车"))
        self.cartype.setItemText(14, _translate("MainWindow", "五型车"))
        self.cartype.setItemText(15, _translate("MainWindow", "特货1"))
        self.cartype.setItemText(16, _translate("MainWindow", "特货2"))
        self.cartype.setItemText(17, _translate("MainWindow", "特货3"))
        self.cartype.setItemText(18, _translate("MainWindow", "特货4"))
        self.cartype.setItemText(19, _translate("MainWindow", "特货5"))
        self.label_3.setText(_translate("MainWindow", "重量"))
        self.label_4.setText(_translate("MainWindow", "入口站"))
        self.label_5.setText(_translate("MainWindow", "出口站"))
        self.label_8.setText(_translate("MainWindow", "货物"))
        self.label_9.setText(_translate("MainWindow", "轴数"))
        self.label_10.setText(_translate("MainWindow", "时间"))
        self.label_12.setText(_translate("MainWindow", "金额"))
        self.amount.setPlaceholderText(_translate("MainWindow", "00.00"))
        self.calculateillegal.setText(_translate("MainWindow", "计算违规因子"))
        self.label_6.setText(_translate("MainWindow", "车辆快照"))
        self.store2mysql.setText(_translate("MainWindow", "存储记录到数据库"))
        self.menu_2.setTitle(_translate("MainWindow", "查看"))
        self.menu_3.setTitle(_translate("MainWindow", "我的"))
        self.menu.setTitle(_translate("MainWindow", "功能"))
        self.mysqlquerymode.setText(_translate("MainWindow", "进入数据库查询模式"))
        self.read_associate.setText(_translate("MainWindow", "查看关联规则文档"))
        self.read_help.setText(_translate("MainWindow", "查看帮助文档"))
        self.mysql_pattern.setText(_translate("MainWindow", "进入数据库查询模式"))
        self.mine_rules.setText(_translate("MainWindow", "关联规则挖掘"))
        self.update_modelparams.setText(_translate("MainWindow", "模型参数更新"))
        self.user_info.setText(_translate("MainWindow", "用户信息"))
        self.read_soft_info.setText(_translate("MainWindow", "查看版本信息"))

from ui import lvtong_rc
