# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'online_rules.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 188)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 391, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.miningitem2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.miningitem2.setObjectName("miningitem2")
        self.miningitem2.addItem("")
        self.miningitem2.setItemText(0, "")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.miningitem2.addItem("")
        self.horizontalLayout.addWidget(self.miningitem2)
        self.miningitem1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.miningitem1.setObjectName("miningitem1")
        self.miningitem1.addItem("")
        self.miningitem1.setItemText(0, "")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.miningitem1.addItem("")
        self.horizontalLayout.addWidget(self.miningitem1)
        self.miningitem3 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.miningitem3.setObjectName("miningitem3")
        self.miningitem3.addItem("")
        self.miningitem3.setItemText(0, "")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.miningitem3.addItem("")
        self.horizontalLayout.addWidget(self.miningitem3)
        self.miningitem4 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.miningitem4.setObjectName("miningitem4")
        self.miningitem4.addItem("")
        self.miningitem4.setItemText(0, "")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.miningitem4.addItem("")
        self.horizontalLayout.addWidget(self.miningitem4)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 15, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.startmining = QtWidgets.QPushButton(Form)
        self.startmining.setGeometry(QtCore.QRect(290, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startmining.setFont(font)
        self.startmining.setObjectName("startmining")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "关联规则在线挖掘"))
        self.miningitem2.setItemText(1, _translate("Form", "车型"))
        self.miningitem2.setItemText(2, _translate("Form", "轴数"))
        self.miningitem2.setItemText(3, _translate("Form", "重量"))
        self.miningitem2.setItemText(4, _translate("Form", "金额"))
        self.miningitem2.setItemText(5, _translate("Form", "出口收费站"))
        self.miningitem2.setItemText(6, _translate("Form", "入口站"))
        self.miningitem2.setItemText(7, _translate("Form", "交易时间"))
        self.miningitem2.setItemText(8, _translate("Form", "货物"))
        self.miningitem2.setItemText(9, _translate("Form", "车辆归属地"))
        self.miningitem1.setItemText(1, _translate("Form", "车型"))
        self.miningitem1.setItemText(2, _translate("Form", "轴数"))
        self.miningitem1.setItemText(3, _translate("Form", "重量"))
        self.miningitem1.setItemText(4, _translate("Form", "金额"))
        self.miningitem1.setItemText(5, _translate("Form", "出口收费站"))
        self.miningitem1.setItemText(6, _translate("Form", "入口站"))
        self.miningitem1.setItemText(7, _translate("Form", "交易时间"))
        self.miningitem1.setItemText(8, _translate("Form", "货物"))
        self.miningitem1.setItemText(9, _translate("Form", "车辆归属地"))
        self.miningitem3.setItemText(1, _translate("Form", "车型"))
        self.miningitem3.setItemText(2, _translate("Form", "轴数"))
        self.miningitem3.setItemText(3, _translate("Form", "重量"))
        self.miningitem3.setItemText(4, _translate("Form", "金额"))
        self.miningitem3.setItemText(5, _translate("Form", "出口收费站"))
        self.miningitem3.setItemText(6, _translate("Form", "入口站"))
        self.miningitem3.setItemText(7, _translate("Form", "交易时间"))
        self.miningitem3.setItemText(8, _translate("Form", "货物"))
        self.miningitem3.setItemText(9, _translate("Form", "车辆归属地"))
        self.miningitem4.setItemText(1, _translate("Form", "车型"))
        self.miningitem4.setItemText(2, _translate("Form", "轴数"))
        self.miningitem4.setItemText(3, _translate("Form", "重量"))
        self.miningitem4.setItemText(4, _translate("Form", "金额"))
        self.miningitem4.setItemText(5, _translate("Form", "出口收费站"))
        self.miningitem4.setItemText(6, _translate("Form", "入口站"))
        self.miningitem4.setItemText(7, _translate("Form", "交易时间"))
        self.miningitem4.setItemText(8, _translate("Form", "货物"))
        self.miningitem4.setItemText(9, _translate("Form", "车辆归属地"))
        self.label.setText(_translate("Form", "选择需要寻找规则的特征维度（可选择二到四维）"))
        self.startmining.setText(_translate("Form", "开始挖掘"))

